#!/usr/bin/env node

// Copyright 2014 Lawrence Kesteloot

var Window = require("./window");
var input = require("./input");
var trace = require("./trace");

if (process.argv.length <= 2) {
    console.log("usage: pad filename");
} else if (process.argv[2] === "--trace") {
    // Monitor the tracing port.
    trace.monitor();
} else {
    var window = new Window();
    var filename = process.argv[2];
    window.panes[0].loadFile(filename, function () {
        // window.panes[1].setDoc(window.panes[0].doc);
    });
    input.start();
}
