#!/usr/bin/env node

// Copyright 2014 Lawrence Kesteloot

var path = require("path");
var Window = require("./window");
var input = require("./input");

if (process.argv.length <= 2) {
    console.log("usage: pad filename");
} else {
    var window = new Window();
    var filename = process.argv[2];
    var pathname = path.resolve(filename);
    window.panes[0].loadFile(pathname, function () {
        window.panes[1].setDoc(window.panes[0].doc);
    });
    input.start();
}
